### ISSUE TITLE
Error during response conversion: value of type "_JsonMap"

### ISSUE THREAD

**Issue by SosthenG** [epam-cross-platform-lab/swagger-dart-code-generator#147]
Hi,
I'm trying to make this work with my Flutter web project but I always have the same error: the response does not seem to be converted to the targeted object type.

I'm expecting a result of type "AccessToken" for which the generated class is the following:
```
@JsonSerializable(explicitToJson: true)
class AccessToken {
  AccessToken({
    this.token,
    this.refreshToken,
  });

  factory AccessToken.fromJson(Map<String, dynamic> json) =>
      _$AccessTokenFromJson(json);

  @JsonKey(name: 'token')
  final String token;
  @JsonKey(name: 'refresh_token')
  final String refreshToken;
  static const fromJsonFactory = _$AccessTokenFromJson;
  static const toJsonFactory = _$AccessTokenToJson;
  Map<String, dynamic> toJson() => _$AccessTokenToJson(this);
}

AccessToken _$AccessTokenFromJson(Map<String, dynamic> json) {
  return AccessToken(
    token: json['token'] as String,
    refreshToken: json['refresh_token'] as String,
  );
}

Map<String, dynamic> _$AccessTokenToJson(AccessToken instance) =>
    <String, dynamic>{
      'token': instance.token,
      'refresh_token': instance.refreshToken,
    };
```

I'm calling this generated method (.swagger.chopper.dart) which looks fine to me too:
```
  Future<Response<AccessToken>> authenticate({Credentials body}) {
    final $url = '/token';
    final $body = body;
    final $request = Request('POST', $url, client.baseUrl, body: $body);
    return client.send<AccessToken, AccessToken>($request);
  }
```

I took a look at the raw response body, it has the right format:
```
{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MTY3ODM3ODYsImV4cCI6MTYxOTM3NTc4Niwicm9sZXMiOlsiUk9MRV9TVVBFUl9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluIn0.PgoJMJqvt-wDRInhdseqxBXw68dKr3RtOWN3nI1uRJj600ixoF1WXM0Z_IMTNrp73nHpvo9jU6TqDRRJqORhIUCDXFsEGL2r-3IUbqU8FLPzMe2LQvW9CO5qWw3Pwuo41Ozi3X-sFEVhT0orE3G5emvgBmabXfXmdpYRti92DZmDK5SPV6Csb_e5qVyPzFmsQkjnu3sUfqjpdfah23Dd7dSbl_RQ-nR8aFTRqPua_2M3lpBUuV8QFOLD7ASuwb50asAgOe_ZScFaMIMc2HxMRUo8VFUArrzI_-y0ZDBb8fId_4DF1MpWak46gQxjF8A9fPzSkzn-6oj6tv2ZMCFGwwA6lSW4hXr3RxI5ibNkjclb2XIEfzGPCy32pnY-Jvg0p3YYXJ4IR4TsfillCfU-jp2ld5B_9fYyXQ5GUvOD5nxKMccRsb2L9rOyoGp_gE2LRVqFD2elS9YmV0Kucf1-jSXnsamDnWJvUFPolZvuCqNHXTa2UpxoIk4EYjMGxtWxWltbrm0kS3-5r5Of7DtUSZmLU_sj-mkmzkGJkiCOg9kUuc3kWU9oh5sNh5k5MHNBbcunU9EVYDV-W4EbTBiiOiyFkrBjrSaymI-XXVFnLUQ5ZZh0t3xzHWbUxHr8PjgLMFwMK_kMexX2fyaH605O6-PE1cb9Z0rcg2rcX4yqQnY","refresh_token":"7f96a3a7f92d0c13988d43f1ef3556a30d68ccc40bd5a6fdea015cd6f1cfb38c123a1b7d5790e50602f3f3730d80bb5915413c3e9838275ac5a72706f85d5c56"}
```

But I always have this error before the return of the result:
```
Error: Expected a value of type 'AccessToken', but got one of type '_JsonMap'
    at Object.throw_ [as throw] (http://localhost:34499/dart_sdk.js:5334:11)
    at Object.castError (http://localhost:34499/dart_sdk.js:5305:15)
    at Object.cast [as as] (http://localhost:34499/dart_sdk.js:5621:17)
    at dart.LegacyType.new.as (http://localhost:34499/dart_sdk.js:7219:60)
    at interceptor.JsonConverter.new.decodeJson (http://localhost:34499/packages/chopper/src/interceptor.dart.lib.js:348:84)
    at interceptor.JsonConverter.new.convertResponse (http://localhost:34499/packages/chopper/src/interceptor.dart.lib.js:351:79)
    at _decodeResponse (http://localhost:34499/packages/chopper/src/interceptor.dart.lib.js:501:46)
    at _decodeResponse.next (<anonymous>)
    at runBody (http://localhost:34499/dart_sdk.js:39052:34)
    at Object._async [as async] (http://localhost:34499/dart_sdk.js:39083:7)
    at base.ChopperClient.new.[_decodeResponse] (http://localhost:34499/packages/chopper/src/interceptor.dart.lib.js:500:20)
    at base.ChopperClient.new._handleSuccessResponse (http://localhost:34499/packages/chopper/src/interceptor.dart.lib.js:558:50)
    at _handleSuccessResponse.next (<anonymous>)
    at runBody (http://localhost:34499/dart_sdk.js:39052:34)
    at Object._async [as async] (http://localhost:34499/dart_sdk.js:39083:7)
    at base.ChopperClient.new.[_handleSuccessResponse] (http://localhost:34499/packages/chopper/src/interceptor.dart.lib.js:554:20)
    at base.ChopperClient.new.send (http://localhost:34499/packages/chopper/src/interceptor.dart.lib.js:595:52)
    at send.next (<anonymous>)
    at http://localhost:34499/dart_sdk.js:39032:33
    at _RootZone.runUnary (http://localhost:34499/dart_sdk.js:38889:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:34499/dart_sdk.js:33875:29)
    at handleValueCallback (http://localhost:34499/dart_sdk.js:34435:49)
    at Function._propagateToListeners (http://localhost:34499/dart_sdk.js:34473:17)
    at _Future.new.[_completeWithValue] (http://localhost:34499/dart_sdk.js:34315:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:34499/dart_sdk.js:34338:35)
    at Object._microtaskLoop (http://localhost:34499/dart_sdk.js:39176:13)
    at _startMicrotaskLoop (http://localhost:34499/dart_sdk.js:39182:13)
    at http://localhost:34499/dart_sdk.js:34689:9
```

Any idea what I'm doing wrong?
Thanks.

**Comment by fryette** [comment]
Is it possible to share the swagger file?

**Comment by SosthenG** [comment]
Sure:
```
{
  "openapi": "3.0.0",
  "info": {
    "title": "IWI",
    "description": "I Want It! API",
    "version": "1.0.0"
  },
  "paths": {
    "/token": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Authenticate user and return JWT access and refresh tokens",
        "operationId": "authenticate",
        "requestBody": {
          "description": "User credentials",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Credentials"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Login successful",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AccessToken"
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          }
        }
      }
    },
    "/token/refresh": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Refresh a JWT token",
        "operationId": "refreshToken",
        "requestBody": {
          "description": "User credentials",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RefreshToken"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Refresh successful",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AccessToken"
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Credentials": {
        "required": [
          "username",
          "password"
        ],
        "properties": {
          "username": {
            "type": "string",
            "example": "username"
          },
          "password": {
            "type": "string",
            "example": "password"
          }
        },
        "type": "object"
      },
      "AccessToken": {
        "required": [
          "token",
          "refresh_token"
        ],
        "properties": {
          "token": {
            "description": "The JWT access token",
            "type": "string",
            "example": "mfGejpZHWcNRg10JjyXefq8HNPi9pDk64OS8b0Zw8H9vztQE0Xx12c0Im3vkfWEgiBzbWqLqrmFBKrcEX6iN36MmXjGPnqXzfjN20zFxmTDSgVuldUrC9GlkI"
          },
          "refresh_token": {
            "description": "The JWT refresh token",
            "type": "string",
            "example": "ODhkOTNlNzA4MDVjNGY2ODE4ZDE1ZjNkNjU4OGE0MzZjYmJmNWM3NmMzMzNlMTNmNzRlNTcxOWUzMTIyZTM0Ng"
          }
        },
        "type": "object"
      },
      "RefreshToken": {
        "required": [
          "refresh_token"
        ],
        "properties": {
          "refresh_token": {
            "description": "The JWT refresh token",
            "type": "string",
            "example": "ODhkOTNlNzA4MDVjNGY2ODE4ZDE1ZjNkNjU4OGE0MzZjYmJmNWM3NmMzMzNlMTNmNzRlNTcxOWUzMTIyZTM0Ng"
          }
        },
        "type": "object"
      },
      "Error": {
        "properties": {
          "code": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          }
        },
        "type": "object"
      }
    },
    "responses": {
      "UnexpectedError": {
        "description": "Unexpected Http Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Error"
            }
          }
        }
      },
      "NotFound": {
        "description": "Not Found",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Error"
            }
          }
        }
      },
      "Unauthorized": {
        "description": "Unauthorized",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Error"
            }
          }
        }
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "bearerFormat": "JWT",
        "scheme": "bearer"
      }
    }
  },
  "security": [
    {
      "Bearer": []
    }
  ]
}
```

**Comment by Vovanella95** [comment]
Hi @SosthenG ,

I will check it today

**Comment by Vovanella95** [comment]
Hi again! I've checked your case. I don't have API so I added next line to json_map.swagger.chopper.dart:

```
final response = http.Response("""
    {\"token\": \"sdsdsdsd\"}
    """, 200);
```
It's line 296.

I've made request and received my fake response

```
final result = service.tokenPost(body: Credentials()).then((value) {
    final tt = value;
  });
```

In my case tt is correct value. So possible swagger is not correct. 

https://sun9-73.userapi.com/impf/qvvBmZz3lROgggmHESTDzDCHAdrxB5XcdcVvhw/t47Ieo2nKEs.jpg?size=569x305&quality=96&sign=83294ee6c062461a77420d5f7bea1ee7&type=album (Please see image)


To sumamrize looks like swagger generator works well. Can you please share response body?

**Comment by SosthenG** [comment]
Hi, thanks for testing!
I joined my response body to my initial message, here is an example of what I'm receiving (this is a dump from the response body as received by the http client):
```
{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MTY3ODM3ODYsImV4cCI6MTYxOTM3NTc4Niwicm9sZXMiOlsiUk9MRV9TVVBFUl9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluIn0.PgoJMJqvt-wDRInhdseqxBXw68dKr3RtOWN3nI1uRJj600ixoF1WXM0Z_IMTNrp73nHpvo9jU6TqDRRJqORhIUCDXFsEGL2r-3IUbqU8FLPzMe2LQvW9CO5qWw3Pwuo41Ozi3X-sFEVhT0orE3G5emvgBmabXfXmdpYRti92DZmDK5SPV6Csb_e5qVyPzFmsQkjnu3sUfqjpdfah23Dd7dSbl_RQ-nR8aFTRqPua_2M3lpBUuV8QFOLD7ASuwb50asAgOe_ZScFaMIMc2HxMRUo8VFUArrzI_-y0ZDBb8fId_4DF1MpWak46gQxjF8A9fPzSkzn-6oj6tv2ZMCFGwwA6lSW4hXr3RxI5ibNkjclb2XIEfzGPCy32pnY-Jvg0p3YYXJ4IR4TsfillCfU-jp2ld5B_9fYyXQ5GUvOD5nxKMccRsb2L9rOyoGp_gE2LRVqFD2elS9YmV0Kucf1-jSXnsamDnWJvUFPolZvuCqNHXTa2UpxoIk4EYjMGxtWxWltbrm0kS3-5r5Of7DtUSZmLU_sj-mkmzkGJkiCOg9kUuc3kWU9oh5sNh5k5MHNBbcunU9EVYDV-W4EbTBiiOiyFkrBjrSaymI-XXVFnLUQ5ZZh0t3xzHWbUxHr8PjgLMFwMK_kMexX2fyaH605O6-PE1cb9Z0rcg2rcX4yqQnY","refresh_token":"7f96a3a7f92d0c13988d43f1ef3556a30d68ccc40bd5a6fdea015cd6f1cfb38c123a1b7d5790e50602f3f3730d80bb5915413c3e9838275ac5a72706f85d5c56"}
```

May be flutter for web not supported or something?
I'm using Flutter 2.0.3 (stable) with Dart 2.12.2 if that matters.

Doing the same test you did, I never go in the `final tt = value;` breakpoint, the exception is thrown before.
Here is my full generated code. If you have the same on your side, it's probably a compatibility issue with my version/Flutter web?

[generated.zip](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/files/6220505/generated.zip)

**Comment by Vovanella95** [comment]
@SosthenG  I've used your code and catched same issue. Let me check what happened.

**Comment by Vovanella95** [comment]
@SosthenG  Bingo! I have understand your problem! Please add with_converter: true parameter to use generated mapping. 

Not correct:
```
final newClient = ChopperClient(
        services: [_$Iwi()],
        converter: chopper.JsonConverter(),
        baseUrl: 'https://google.com');
    return _$Iwi(newClient);
```


Correct: 
final newClient = ChopperClient(
        services: [_$Iwi()],
        converter: JsonSerializableConverter(),
        baseUrl: 'https://google.com');
    return _$Iwi(newClient);

Please close the issue if it helps!

**Comment by SosthenG** [comment]
From what I understood, `true` is the default value for `with_converter` and I did not changed it.
Passing `with_converter: true` explicitly does not solve the issue: the converter is still set to `chopper.JsonConverter()`.

However, I had set `with_base_url: false` and removing it from my conf does make it work as expected, so I'm guessing this base_url param is doing something it shouldn't do.
I'll just remove my `with_base_url` param as a work around!

**Comment by Vovanella95** [comment]
You're right, converter generation depends from with_base_url. It looks little bit not logical. We will recheck it. Can we close this issue?

**Comment by SosthenG** [comment]
Sure, thanks for your help!

**Comment by Vovanella95** [comment]
Thank YOU for raising issue. Let's make swagger generator great!
